query mainPage($slug: String!) {
  page(input: { slug: $slug }) {
    blocks {
      id
      name
      type
      block {
        type
        data {
          key
          type
          value
          items {
            type
            data {
              key
              value
              type
            }
          }
        }
      }
    }
  }
}

mutation createRequest($input: CreateRequestInput!) {
  createRequest(input: $input) {
    message
    status
  }
}
